Fix AppleClang: Stock `aligned_alloc`
Compiling heFFTe 2.4.0 with AppleClang 16.0.6 on macOS 13.4 raises:
```
include/stock_fft/heffte_stock_allocator.h:43:46: error: use of undeclared identifier 'aligned_alloc'
            return reinterpret_cast<pointer>(aligned_alloc(alignof(F), n*sizeof(F)));
                                             ^
```

This adds the missing include and uses the C++ variant of the
function.